import Foundation

/// Reads metadata out of an *encrypted file's own* `sops:` block — a
/// fundamentally different, narrower problem than parsing a user-authored
/// `.sops.yaml`, which is why it is not covered by the migration to
/// `SopsBridge.lookupCreationRule` described in `ProjectHealthCheck`'s doc
/// comment. Two things make it narrower:
///
/// 1. The input is machine-generated by sops's own serializer
///    (`stores/yaml/store.go`, `stores/metadata.go` in getsops/sops
///    v3.13.3), never hand-typed. It has exactly one shape: fixed 4-space
///    indent, no comments, no flow sequences split or otherwise, no
///    creative formatting choices — the entire "a real user writes YAML in
///    many equally-valid ways" problem that made `.sops.yaml` parsing
///    fragile does not exist here.
/// 2. What this reads is far narrower: a handful of known top-level keys
///    under `sops:`, each with a small, fixed set of sub-fields. There is
///    no indentation-sensitive rule/key state machine, no bracket
///    balancing, no multi-line joining.
///
/// That said, this scanner was reviewed for the *same class* of bug the
/// `.sops.yaml` parser had — scope creep from "read sops's own metadata"
/// into "read anything that looks similar" — and one real instance was
/// found and fixed: `recipients(inEncryptedFile:)` used to scan the *whole*
/// file for any line starting with `recipient:`, not just inside the
/// `sops:` block. Since sops only ever encrypts *values*, never *keys*, a
/// project's own plaintext data can legitimately have a field literally
/// named `recipient` (e.g. an email/payment "recipient" field) — after
/// encryption that becomes `recipient: ENC[...]`, which the old, unscoped
/// scan would have swallowed whole as if `ENC[AES256_GCM,...]` were a real
/// age public key. Both functions are now scoped to the `sops:` block via
/// the shared `sopsBlockLines(in:)` helper, closing that gap. See
/// `EncryptedFileMetadataTests.swift` for the regression test.
enum EncryptedFileMetadata {

    /// The full set of backend field names getsops/sops v3.13.3 itself
    /// writes for a non-age key (`stores.metadata` in `stores/stores.go`):
    /// `pgp`, `kms`, `gcp_kms`, `hckms`, `azure_kv`, `hc_vault`,
    /// `key_groups`. Shared between the YAML, dotenv, JSON and INI readers
    /// below — all four scan for the same field names, just flattened (or
    /// not) differently on disk. See `nonAgeBackends(inEncryptedFile:)`'s
    /// doc comment for what finding one means.
    ///
    /// Ordered, not a bare `Set`: the JSON and INI readers iterate this list
    /// to build `found` (a `[String: Any]`/an unordered flattened-key scan
    /// has no natural on-disk order of its own the way YAML's/dotenv's line
    /// order does), and `Set`'s iteration order is not guaranteed stable —
    /// a nondeterministic result here would make a multi-backend fixture's
    /// test flaky for a reason that has nothing to do with the code under
    /// test.
    private static let nonAgeBackendKeysOrdered =
        ["pgp", "kms", "gcp_kms", "hckms", "azure_kv", "hc_vault", "key_groups"]
    private static let nonAgeBackendKeys = Set(nonAgeBackendKeysOrdered)

    /// Public keys a sops-encrypted file is wrapped for, read from its
    /// `sops.age[].recipient` metadata.
    ///
    /// Dispatches on the tail's own shape rather than taking a `format`
    /// parameter: `sopsBlockLines(in:)` returns lines only for a document
    /// carrying a YAML `sops:` block, so a non-empty result already answers
    /// "this is YAML" with no separate flag to keep in sync — and no call
    /// site has to spell `SopsFileFormat` just to read a file it already
    /// has the bytes of. See `ProjectScanner.classify` for where the four
    /// shapes are actually told apart (structurally, via
    /// `SopsMetadataShape`) before a `SniffedFile` is ever produced.
    static func recipients(inEncryptedFile text: String) -> [String] {
        let yamlLines = sopsBlockLines(in: text)
        guard !yamlLines.isEmpty else { return nonYAMLRecipients(text) }
        return yamlLines.compactMap { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard trimmed.hasPrefix("- recipient:") || trimmed.hasPrefix("recipient:") else { return nil }
            guard let colon = trimmed.firstIndex(of: ":") else { return nil }
            let value = unquote(String(trimmed[trimmed.index(after: colon)...]))
            return value.isEmpty ? nil : value
        }
    }

    /// Non-age key backends actually present in an encrypted file's own
    /// `sops:` metadata block — see `nonAgeBackendKeys`'s doc comment for
    /// the field names. This is ground truth about how the *file itself* is
    /// protected right now — independent of what its governing `.sops.yaml`
    /// rule declares, which can drift out of sync with what was actually
    /// run. A file whose own metadata shows one of these cannot have its
    /// recipients fully verified by this app: it only ever holds age keys,
    /// never a PGP private key, a cloud IAM credential, or a Vault token.
    ///
    /// Dispatches on shape the same way `recipients(inEncryptedFile:)` does
    /// — see that function's doc comment.
    static func nonAgeBackends(inEncryptedFile text: String) -> [String] {
        let yamlLines = sopsBlockLines(in: text)
        guard !yamlLines.isEmpty else { return nonYAMLNonAgeBackends(text) }
        var found: [String] = []
        for line in yamlLines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed == "sops:" { continue }
            let (key, value) = split(trimmed)
            guard Self.nonAgeBackendKeys.contains(key) else { continue }
            let v = value.trimmingCharacters(in: .whitespaces)
            if v != "[]", v != "{}", !found.contains(key) {
                found.append(key)
            }
        }
        return found
    }

    // MARK: - Non-YAML dispatch

    /// Routes to whichever non-YAML store's shape `text` actually has, for
    /// `recipients(inEncryptedFile:)`. `nonYAMLKind` is the exact same
    /// structural check `ProjectScanner.classify` already used to decide
    /// this text belongs in `tree.encrypted` at all and which
    /// `SopsFileFormat` its `SniffedFile` carries — calling it again here,
    /// rather than threading that answer down as a parameter, is what keeps
    /// the two readings from ever being able to drift apart (see
    /// `SopsBlockAgreementTests` at the bottom of `SopsMetadataShapeTests
    /// .swift` for why two independent readings of "what shape is this"
    /// disagreeing is exactly the class of bug this file exists to avoid).
    /// `nil` is unreached in practice — every caller of this type only ever
    /// has text one of the three structural checks already matched — but is
    /// handled honestly (no recipients) rather than force-unwrapped.
    private static func nonYAMLRecipients(_ text: String) -> [String] {
        switch SopsMetadataShape.nonYAMLKind(text) {
        case .dotenv: return recipientsFromDotenv(text)
        case .json: return recipientsFromJSON(text)
        case .ini: return recipientsFromINI(text)
        case nil: return []
        }
    }

    /// The `nonAgeBackends(inEncryptedFile:)` counterpart to
    /// `nonYAMLRecipients(_:)` — see that function's doc comment.
    private static func nonYAMLNonAgeBackends(_ text: String) -> [String] {
        switch SopsMetadataShape.nonYAMLKind(text) {
        case .dotenv: return nonAgeBackendsFromDotenv(text)
        case .json: return nonAgeBackendsFromJSON(text)
        case .ini: return nonAgeBackendsFromINI(text)
        case nil: return []
        }
    }

    // MARK: - dotenv

    /// getsops/sops's dotenv store never writes a `sops:` block: instead
    /// every metadata field is flattened into its own `sops_`-prefixed
    /// `KEY=value` line at column 0 (`stores/metadata.go`'s
    /// `SerializeMetadata` with `MetadataFlattenFull`, `stores/flatten.go`'s
    /// `flattenTreeBranch` — `__map_<key>` for a nested field, `__list_<n>`
    /// for a list element, chained for a nested list-of-maps). Verified
    /// against the real in-process bridge, not just the Go source: encrypting
    /// `FOO=bar\nBAZ=qux\n` for one age recipient produces exactly
    /// ```
    /// FOO=ENC[...]
    /// BAZ=ENC[...]
    /// sops_age__list_0__map_enc=-----BEGIN AGE ENCRYPTED FILE-----\n...
    /// sops_age__list_0__map_recipient=age1...
    /// sops_lastmodified=2026-09-01T08:02:32Z
    /// sops_mac=ENC[...]
    /// sops_unencrypted_suffix=_unencrypted
    /// sops_version=3.13.3
    /// ```
    /// — one `sops_age__list_<n>__map_recipient=` line per age recipient, no
    /// `sops:` line anywhere. See `SopsMetadataShapeTests` for the fixture
    /// this was verified against and `SopsMetadataShape.isDotenvMetadata`
    /// for the structural check that decides a tail is this shape at all
    /// before either function here is ever called.
    private static func dotenvSopsMetadataLines(in text: String) -> [(key: String, value: String)] {
        LineEndings.lines(of: text).compactMap { line in
            guard line.hasPrefix("sops_"), let equals = line.firstIndex(of: "=") else { return nil }
            return (String(line[line.startIndex..<equals]), String(line[line.index(after: equals)...]))
        }
    }

    /// `sops_age__list_<n>__map_recipient=<value>` for every age entry,
    /// value order following the lines as they appear on disk. See
    /// `dotenvSopsMetadataLines`'s doc comment for the shape this scans.
    private static func recipientsFromDotenv(_ text: String) -> [String] {
        dotenvSopsMetadataLines(in: text).compactMap { entry in
            guard entry.key.hasPrefix("sops_age__"), entry.key.hasSuffix("__map_recipient") else { return nil }
            return entry.value.isEmpty ? nil : entry.value
        }
    }

    /// The dotenv counterpart to the YAML loop in
    /// `nonAgeBackends(inEncryptedFile:)`: every flattened key names its
    /// *top-level* metadata field first (`dotenvTopLevelSegment(of:)`), and a
    /// key backend is present exactly when that field is one of
    /// `nonAgeBackendKeys` — regardless of how deep the value nests beneath
    /// it (`sops_key_groups__list_0__map_pgp__list_0__map_fp=` still reduces
    /// to `key_groups`, matching the YAML reader's own behaviour of flagging
    /// `key_groups` itself rather than reaching into it — see that
    /// function's fixture-backed test). Unlike the YAML reader, there is no
    /// `v != "[]"` guard to make: sops's flattener never emits a key for an
    /// empty list at all (`flattenDescendArray` over zero elements appends
    /// nothing), so a backend's absence from every line here already means
    /// it protects nothing in this file.
    private static func nonAgeBackendsFromDotenv(_ text: String) -> [String] {
        var found: [String] = []
        for entry in dotenvSopsMetadataLines(in: text) {
            // Every `entry.key` here already passed `dotenvSopsMetadataLines`'s
            // own `hasPrefix("sops_")` filter, so the prefix is always there
            // to drop.
            let segment = Self.topLevelSegment(of: entry.key.dropFirst("sops_".count))
            guard Self.nonAgeBackendKeys.contains(segment), !found.contains(segment) else { continue }
            found.append(segment)
        }
        return found
    }

    /// `key_groups__list_0__map_pgp__list_0__map_fp` → `key_groups`;
    /// `mac` → `mac`. Cuts at the first `__map_`/`__list_` separator
    /// (whichever comes first) — see `flattenTreeBranch`'s doc comment above
    /// for where those separators come from. A key with neither (every
    /// scalar field: `mac`, `version`, `lastmodified`, `unencrypted_suffix`,
    /// `shamir_threshold`) returns unchanged.
    ///
    /// Shared by the dotenv reader above (which strips its `sops_` prefix
    /// before calling this — see `nonAgeBackendsFromDotenv`) and the INI
    /// reader below (whose flattened keys carry no such prefix to strip:
    /// sops's INI store already isolates them under a literal `[sops]`
    /// section instead — see `iniSopsMetadataEntries`'s doc comment). Both
    /// stores share the same `flattenTreeBranch` separators underneath a
    /// different top-level wrapper, so one function reads both.
    private static func topLevelSegment(of key: Substring) -> String {
        let candidates = [
            key.range(of: "__map_")?.lowerBound,
            key.range(of: "__list_")?.lowerBound,
        ].compactMap { $0 }
        guard let cut = candidates.min() else { return String(key) }
        return String(key[..<cut])
    }

    // MARK: - JSON

    /// getsops/sops's JSON store never flattens anything: it keeps its
    /// metadata as a genuine nested JSON object under a literal top-level
    /// `"sops"` key (`MetadataFlattenNone`, `stores/json/store.go`'s
    /// `LoadEncryptedFile`) — the same tree shape `age`/`pgp`/`kms`/…
    /// entries have in YAML, just written as JSON instead of flattened
    /// `KEY=value` lines the way dotenv and INI are. So this reads it with
    /// `JSONSerialization` rather than scanning lines, the one reader here
    /// that does not share `LineEndings.lines(of:)` with the rest of this
    /// file.
    ///
    /// Verified against the real `sops` binary — SOPS-38 phase F2 task 3,
    /// captured once by hand to see the genuine *multi*-recipient shape
    /// (`EncryptedFileMetadataJSONTests` proves the round trip against the
    /// real in-process bridge instead, which also supports more than one
    /// recipient — this fixture just happened to be pulled from the CLI
    /// first). Encrypting a small object for two age recipients produces a
    /// document whose plaintext keys carry `ENC[...]` values alongside a
    /// sibling top-level metadata object — described in prose rather than
    /// pasted in as a literal fenced example, because the first draft of
    /// this comment did paste one in, and made this very file the next
    /// false positive `SopsMetadataShapeTests.ownSourceTreeIsNotEncrypted`
    /// exists to catch: `SopsMetadataShape.isJSONMetadata` has no column-0
    /// or exact-line-match protection the way its YAML/dotenv/INI siblings
    /// do — it is a bare substring-plus-whitespace-skip scan — so a doc
    /// comment quoting `"sops":` immediately followed by `{`, with the two
    /// required field-name substrings nearby, satisfies it regardless of
    /// indentation or a leading `///`. Reproduced, then rewritten; the
    /// fixture that pins the real shape lives in `EncryptedFileMetadataJSON
    /// Tests`, where the app does not read it. That metadata object holds:
    /// an `age` array of entries, each an encrypted data key alongside the
    /// recipient's public key; the last-modified timestamp; the document's
    /// MAC; the unencrypted-suffix setting; the sops version — and no
    /// pgp/kms/… entry at all when that backend protects nothing in the
    /// file (`stores.stores.go`'s `omitempty` struct tags: sops's Go struct
    /// never even emits an empty array for one), the exact same
    /// present-or-absent shape `EncryptedFileMetadataDotenvTests
    /// .realDotenvFileHasNoNonAgeBackend` already pins for dotenv.
    /// `EncryptedFileMetadataJSONTests` in the test target round-trips this
    /// through the real in-process bridge, which does support `format:
    /// .json` for a single recipient (`SopsBridgeJSONTests`, F2 task 2).
    private static func jsonSopsBlock(in text: String) -> [String: Any]? {
        guard let data = text.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return nil }
        return object["sops"] as? [String: Any]
    }

    /// `sops.age[].recipient` read straight out of the real JSON object —
    /// no flattened key name to parse, unlike dotenv/INI. See
    /// `jsonSopsBlock(in:)`'s doc comment for the shape.
    private static func recipientsFromJSON(_ text: String) -> [String] {
        guard let sopsBlock = jsonSopsBlock(in: text),
              let ageEntries = sopsBlock["age"] as? [[String: Any]] else { return [] }
        return ageEntries.compactMap { entry in
            guard let recipient = entry["recipient"] as? String, !recipient.isEmpty else { return nil }
            return recipient
        }
    }

    /// The JSON counterpart to `nonAgeBackends(inEncryptedFile:)`'s YAML
    /// loop and `nonAgeBackendsFromDotenv`: each backend key is present or
    /// absent as a real JSON key, so this is a membership test against
    /// `nonAgeBackendKeysOrdered` rather than a line scan. The `[]`/`{}`
    /// emptiness guard the YAML reader needs (a hand-authored `.sops.yaml`
    /// backend list could theoretically be edited down to an explicit empty
    /// array) is kept here too, defensively, even though `jsonSopsBlock`'s
    /// own doc comment notes sops's real writer never emits one — an
    /// explicitly empty value read back from disk should not be flagged
    /// either way it got there.
    private static func nonAgeBackendsFromJSON(_ text: String) -> [String] {
        guard let sopsBlock = jsonSopsBlock(in: text) else { return [] }
        var found: [String] = []
        for key in Self.nonAgeBackendKeysOrdered {
            guard let value = sopsBlock[key] else { continue }
            if let array = value as? [Any], array.isEmpty { continue }
            if let object = value as? [String: Any], object.isEmpty { continue }
            found.append(key)
        }
        return found
    }

    // MARK: - INI

    /// getsops/sops's INI store keeps its metadata under a literal `[sops]`
    /// section, with every nested field flattened *below* that section
    /// header rather than fully flattened like dotenv's (`MetadataFlatten
    /// BelowTop`, `stores/ini/store.go`'s `LoadEncryptedFile` /
    /// `stores/metadata.go`'s `ExtractMetadata`) — so an INI flattened key
    /// carries no `sops_` prefix at all; the section header already scopes
    /// it. Verified against the real `sops` binary, captured once by hand
    /// for the genuine multi-recipient shape the same way `jsonSopsBlock`'s
    /// doc comment describes — `EncryptedFileMetadataINITests` round-trips
    /// this through the real in-process bridge instead (`format: .ini`, F2
    /// task 2): encrypting `[db]\npassword=hunter2\nuser=admin\n` for two
    /// age recipients produces
    /// ```ini
    /// [db]
    /// password = ENC[...]
    /// user     = ENC[...]
    ///
    /// [sops]
    /// age__list_0__map_enc       = -----BEGIN AGE ENCRYPTED FILE-----\n...
    /// age__list_0__map_recipient = age1...
    /// age__list_1__map_enc       = -----BEGIN AGE ENCRYPTED FILE-----\n...
    /// age__list_1__map_recipient = age1...
    /// lastmodified               = ...
    /// mac                        = ENC[...]
    /// unencrypted_suffix         = _unencrypted
    /// version                    = 3.13.3
    /// ```
    /// — keys padded to a common column (the same padding
    /// `SopsMetadataShape.isINIMetadata`'s doc comment already describes for
    /// `mac`/`version`), so each is read up to the first `=` and trimmed
    /// rather than matched literally.
    ///
    /// The **last** `[sops]` section, matching `SopsMetadataShape
    /// .isINIMetadata`'s own last-match rule (see `sopsBlockLines(in:)`'s
    /// doc comment above for why the YAML reader agrees with its own
    /// structural check the same way) — and ended by the next `[section]`
    /// header or EOF, so a user's own INI data cannot smuggle a later
    /// section into this scan.
    private static func iniSopsBlockLines(in text: String) -> [String] {
        let all = LineEndings.lines(of: text).map(String.init)
        guard let headerIndex = all.lastIndex(where: {
            $0.trimmingCharacters(in: .whitespaces) == "[sops]"
        }) else { return [] }

        var lines: [String] = []
        for line in all[(headerIndex + 1)...] {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("["), trimmed.hasSuffix("]") { break }
            lines.append(line)
        }
        return lines
    }

    /// `iniSopsBlockLines(in:)`'s lines, each split at its first `=` and
    /// trimmed of the padding sops writes around it. See that function's
    /// doc comment for the real shape this scans.
    private static func iniSopsMetadataEntries(in text: String) -> [(key: String, value: String)] {
        iniSopsBlockLines(in: text).compactMap { line in
            guard let equals = line.firstIndex(of: "=") else { return nil }
            let key = line[line.startIndex..<equals].trimmingCharacters(in: .whitespaces)
            guard !key.isEmpty else { return nil }
            let value = line[line.index(after: equals)...].trimmingCharacters(in: .whitespaces)
            return (key, value)
        }
    }

    /// `age__list_<n>__map_recipient = <value>` for every age entry — the
    /// INI counterpart to `recipientsFromDotenv`, differing only in that the
    /// key carries no `sops_` prefix to check for. See
    /// `iniSopsMetadataEntries(in:)`'s doc comment for the shape this scans.
    private static func recipientsFromINI(_ text: String) -> [String] {
        iniSopsMetadataEntries(in: text).compactMap { entry in
            guard entry.key.hasPrefix("age__"), entry.key.hasSuffix("__map_recipient") else { return nil }
            return entry.value.isEmpty ? nil : entry.value
        }
    }

    /// The INI counterpart to `nonAgeBackendsFromDotenv`, sharing
    /// `topLevelSegment(of:)` — the only difference is that an INI
    /// flattened key has no `sops_` prefix to strip first, because the
    /// `[sops]` section header already scopes it (see
    /// `iniSopsBlockLines(in:)`'s doc comment). No `[]`/`{}` emptiness guard
    /// here either, for the same reason `nonAgeBackendsFromDotenv` has
    /// none: sops's flattener never emits a key for an empty list at all.
    private static func nonAgeBackendsFromINI(_ text: String) -> [String] {
        var found: [String] = []
        for entry in iniSopsMetadataEntries(in: text) {
            let segment = Self.topLevelSegment(of: entry.key[...])
            guard Self.nonAgeBackendKeys.contains(segment), !found.contains(segment) else { continue }
            found.append(segment)
        }
        return found
    }

    // MARK: - YAML

    /// Extracts just the `sops:` metadata block's lines — started by a line
    /// that is exactly `sops:` at column 0, ended by the next column-0 line
    /// or EOF. Scoping every scan to this block, rather than the whole
    /// file, is what stops a user's own plaintext field name (e.g.
    /// `recipient`, `kms`) from being mistaken for sops metadata; see the
    /// type-level doc comment.
    ///
    /// `LineEndings.lines(of:)`, not `split(separator: "\n")`. Swift treats
    /// `"\r\n"` as a *single* `Character`, so splitting on the `Character`
    /// `"\n"` does not split a CRLF document at all: the whole file came back
    /// as one line, no line ever equalled `"sops:"`, this function returned
    /// nothing, and `recipients(inEncryptedFile:)` reported *no recipients* —
    /// which `ProjectHealthCheck` then rendered as a `.problem` saying the
    /// file "does not list <key> among its recipients" about a file that
    /// lists it perfectly well, with `sops updatekeys` offered as the fix for
    /// a problem that did not exist. sops writes LF, but an editor round-trip
    /// or `git config core.autocrlf=true` is enough to change that, and the
    /// byte-level marker search that classifies the file in the first place
    /// (`ProjectScanner.sopsBlockMarker`, a `Data` search where `\r\n` really
    /// is two bytes) never cared — so a CRLF file reached this function
    /// classified correctly and was then misread. Fourth occurrence of this
    /// gotcha in the project; see `LineEndings` for the full list and for the
    /// guard that now fails the build on the idiom.
    /// The **last** top-level `sops:` block, not the first.
    ///
    /// This used to take the first, while `SopsMetadataShape.isYAMLMetadata`
    /// — the type that decides whether a file is a SOPS document at all —
    /// takes the last. Two readings that can disagree about which block is the
    /// metadata is the defect; agreeing matters more than which one wins.
    ///
    /// **The reason, corrected.** The first version of this comment justified
    /// the change with a document holding two top-level `sops:` keys. A review
    /// checked that against the real CLI and it cannot exist: sops refuses to
    /// read it (`mapping key "sops" already defined`) and refuses to encrypt a
    /// plaintext carrying its own top-level `sops` key ("rename the 'sops'
    /// entry"). The change was right; the story was not.
    ///
    /// The real reason is **multi-document YAML**, measured against sops
    /// 3.13.2: each document gets its own `sops:` block, and taking the first
    /// makes `isYAMLMetadata` walk into the `---` separator at column zero and
    /// return false. Last-match is what keeps multi-document files working.
    ///
    /// A nested `sops:` at deeper indentation is not a hazard either way — the
    /// comparison is against the untrimmed line, so `    sops:` never matches.
    private static func sopsBlockLines(in text: String) -> [String] {
        let all = LineEndings.lines(of: text).map(String.init)
        guard let blockStart = all.lastIndex(where: { $0 == "sops:" }) else { return [] }

        var lines: [String] = [all[blockStart]]
        for line in all[(blockStart + 1)...] {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { lines.append(line); continue }
            if !line.hasPrefix(" ") && !line.hasPrefix("\t") { break }
            lines.append(line)
        }
        return lines
    }

    private static func split(_ entry: String) -> (key: String, value: String) {
        guard let colon = entry.firstIndex(of: ":") else { return (entry, "") }
        let key = String(entry[entry.startIndex..<colon]).trimmingCharacters(in: .whitespaces)
        let value = String(entry[entry.index(after: colon)...]).trimmingCharacters(in: .whitespaces)
        return (key, value)
    }

    private static func unquote(_ value: String) -> String {
        let trimmed = value.trimmingCharacters(in: .whitespaces)
        guard trimmed.count >= 2 else { return trimmed }
        if (trimmed.hasPrefix("\"") && trimmed.hasSuffix("\""))
            || (trimmed.hasPrefix("'") && trimmed.hasSuffix("'")) {
            return String(trimmed.dropFirst().dropLast())
        }
        return trimmed
    }
}
