import Foundation

/// Reads metadata out of an *encrypted file's own* `sops:` block — a
/// fundamentally different, narrower problem than parsing a user-authored
/// `.sops.yaml`, which is why it is not covered by the migration to
/// `SopsBridge.lookupCreationRule` described in `ProjectHealthCheck`'s doc
/// comment. Two things make it narrower:
///
/// 1. The input is machine-generated by sops's own serializer
///    (`stores/yaml/store.go`, `stores/metadata.go` in getsops/sops
///    v3.13.3), never hand-typed. It has exactly one shape: fixed 4-space
///    indent, no comments, no flow sequences split or otherwise, no
///    creative formatting choices — the entire "a real user writes YAML in
///    many equally-valid ways" problem that made `.sops.yaml` parsing
///    fragile does not exist here.
/// 2. What this reads is far narrower: a handful of known top-level keys
///    under `sops:`, each with a small, fixed set of sub-fields. There is
///    no indentation-sensitive rule/key state machine, no bracket
///    balancing, no multi-line joining.
///
/// That said, this scanner was reviewed for the *same class* of bug the
/// `.sops.yaml` parser had — scope creep from "read sops's own metadata"
/// into "read anything that looks similar" — and one real instance was
/// found and fixed: `recipients(inEncryptedFile:)` used to scan the *whole*
/// file for any line starting with `recipient:`, not just inside the
/// `sops:` block. Since sops only ever encrypts *values*, never *keys*, a
/// project's own plaintext data can legitimately have a field literally
/// named `recipient` (e.g. an email/payment "recipient" field) — after
/// encryption that becomes `recipient: ENC[...]`, which the old, unscoped
/// scan would have swallowed whole as if `ENC[AES256_GCM,...]` were a real
/// age public key. Both functions are now scoped to the `sops:` block via
/// the shared `sopsBlockLines(in:)` helper, closing that gap. See
/// `EncryptedFileMetadataTests.swift` for the regression test.
enum EncryptedFileMetadata {

    /// Public keys a sops-encrypted file is wrapped for, read from its
    /// `sops.age[].recipient` metadata.
    static func recipients(inEncryptedFile text: String) -> [String] {
        sopsBlockLines(in: text).compactMap { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard trimmed.hasPrefix("- recipient:") || trimmed.hasPrefix("recipient:") else { return nil }
            guard let colon = trimmed.firstIndex(of: ":") else { return nil }
            let value = unquote(String(trimmed[trimmed.index(after: colon)...]))
            return value.isEmpty ? nil : value
        }
    }

    /// Non-age key backends actually present in an encrypted file's own
    /// `sops:` metadata block, read from the field names getsops/sops v3.13.3
    /// itself writes (`stores.metadata` in `stores/stores.go`): `pgp`, `kms`,
    /// `gcp_kms`, `hckms`, `azure_kv`, `hc_vault`, `key_groups`. This is
    /// ground truth about how the *file itself* is protected right now —
    /// independent of what its governing `.sops.yaml` rule declares, which
    /// can drift out of sync with what was actually run. A file whose own
    /// metadata shows one of these cannot have its recipients fully verified
    /// by this app: it only ever holds age keys, never a PGP private key, a
    /// cloud IAM credential, or a Vault token.
    static func nonAgeBackends(inEncryptedFile text: String) -> [String] {
        let backendKeys: Set<String> = ["pgp", "kms", "gcp_kms", "hckms", "azure_kv", "hc_vault", "key_groups"]
        var found: [String] = []
        for line in sopsBlockLines(in: text) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed == "sops:" { continue }
            let (key, value) = split(trimmed)
            guard backendKeys.contains(key) else { continue }
            let v = value.trimmingCharacters(in: .whitespaces)
            if v != "[]", v != "{}", !found.contains(key) {
                found.append(key)
            }
        }
        return found
    }

    /// Extracts just the `sops:` metadata block's lines — started by a line
    /// that is exactly `sops:` at column 0, ended by the next column-0 line
    /// or EOF. Scoping every scan to this block, rather than the whole
    /// file, is what stops a user's own plaintext field name (e.g.
    /// `recipient`, `kms`) from being mistaken for sops metadata; see the
    /// type-level doc comment.
    ///
    /// `LineEndings.lines(of:)`, not `split(separator: "\n")`. Swift treats
    /// `"\r\n"` as a *single* `Character`, so splitting on the `Character`
    /// `"\n"` does not split a CRLF document at all: the whole file came back
    /// as one line, no line ever equalled `"sops:"`, this function returned
    /// nothing, and `recipients(inEncryptedFile:)` reported *no recipients* —
    /// which `ProjectHealthCheck` then rendered as a `.problem` saying the
    /// file "does not list <key> among its recipients" about a file that
    /// lists it perfectly well, with `sops updatekeys` offered as the fix for
    /// a problem that did not exist. sops writes LF, but an editor round-trip
    /// or `git config core.autocrlf=true` is enough to change that, and the
    /// byte-level marker search that classifies the file in the first place
    /// (`ProjectScanner.sopsBlockMarker`, a `Data` search where `\r\n` really
    /// is two bytes) never cared — so a CRLF file reached this function
    /// classified correctly and was then misread. Fourth occurrence of this
    /// gotcha in the project; see `LineEndings` for the full list and for the
    /// guard that now fails the build on the idiom.
    /// The **last** top-level `sops:` block, not the first.
    ///
    /// This used to take the first, while `SopsMetadataShape.isYAMLMetadata`
    /// — the type that decides whether a file is a SOPS document at all —
    /// takes the last. Two readings that can disagree about which block is the
    /// metadata is the defect; agreeing matters more than which one wins.
    ///
    /// **The reason, corrected.** The first version of this comment justified
    /// the change with a document holding two top-level `sops:` keys. A review
    /// checked that against the real CLI and it cannot exist: sops refuses to
    /// read it (`mapping key "sops" already defined`) and refuses to encrypt a
    /// plaintext carrying its own top-level `sops` key ("rename the 'sops'
    /// entry"). The change was right; the story was not.
    ///
    /// The real reason is **multi-document YAML**, measured against sops
    /// 3.13.2: each document gets its own `sops:` block, and taking the first
    /// makes `isYAMLMetadata` walk into the `---` separator at column zero and
    /// return false. Last-match is what keeps multi-document files working.
    ///
    /// A nested `sops:` at deeper indentation is not a hazard either way — the
    /// comparison is against the untrimmed line, so `    sops:` never matches.
    private static func sopsBlockLines(in text: String) -> [String] {
        let all = LineEndings.lines(of: text).map(String.init)
        guard let blockStart = all.lastIndex(where: { $0 == "sops:" }) else { return [] }

        var lines: [String] = [all[blockStart]]
        for line in all[(blockStart + 1)...] {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { lines.append(line); continue }
            if !line.hasPrefix(" ") && !line.hasPrefix("\t") { break }
            lines.append(line)
        }
        return lines
    }

    private static func split(_ entry: String) -> (key: String, value: String) {
        guard let colon = entry.firstIndex(of: ":") else { return (entry, "") }
        let key = String(entry[entry.startIndex..<colon]).trimmingCharacters(in: .whitespaces)
        let value = String(entry[entry.index(after: colon)...]).trimmingCharacters(in: .whitespaces)
        return (key, value)
    }

    private static func unquote(_ value: String) -> String {
        let trimmed = value.trimmingCharacters(in: .whitespaces)
        guard trimmed.count >= 2 else { return trimmed }
        if (trimmed.hasPrefix("\"") && trimmed.hasSuffix("\""))
            || (trimmed.hasPrefix("'") && trimmed.hasSuffix("'")) {
            return String(trimmed.dropFirst().dropLast())
        }
        return trimmed
    }
}
